export interface NormalizedDataRow {
  campaign_id: number | null;
  campaign_name: string | null;
  ad_group_id: number | null;
  ad_group_name: string | null;
  date: Date | null;
  cost_micros: number | null;
  impressions: number | null;
  clicks: number | null;
  _sdc_received_at: Date | null;
  _sdc_batched_at: Date | null;
  _sdc_deleted_at: Date | null;
  _sdc_extracted_at: Date | null;
  _sdc_sequence: number | null;
  _sdc_table_version: number | null;
  sessions: number | null;
  leads: number | null;
  revenue: number | null;
}
